source 'https://rubygems.org'

gem 'xcodeproj'
gem 'fastlane', '~> 2.222'
gem 'dotenv'

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)